// `claude-distill analyze [--no-auto] [--mock] [--quiet] [--session=X]`
//
// SessionEnd hook이 자동 호출. 사용자가 직접 부를 일은 거의 없음.
//
// 동작 (기본):
//   1. 가장 최근 세션 jsonl을 slice
//   2. claude CLI에 분석 prompt 전달
//   3. confidence:high entry만 markdown에 자동 append
//   4. medium/low entry는 그냥 drop (사용자 손 가지 않게)
//
// 옵션:
//   --no-auto      추출만 하고 stdout에 JSON 출력 (디버깅용)
//   --mock         claude CLI 호출 없이 fake entry 1건 생성
//   --quiet        Hook용 — 아무 출력 안 함
//   --session=X    특정 jsonl 직접 지정

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const crypto = require('crypto');
const cfg = require('./config');
const transcript = require('./transcript');
const store = require('./store');

function parseFlags(args) {
  const flags = {
    quiet: false,
    session: null,
    dryRun: false,
    mock: false,
    auto: true,        // 기본값 — 자동 누적 (CLI 핵심)
    backend: 'auto',   // 'auto' | 'cli' | 'api' — auto는 ANTHROPIC_API_KEY 있으면 api, 없으면 cli
  };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--quiet') flags.quiet = true;
    else if (a === '--dry-run') flags.dryRun = true;
    else if (a === '--mock') flags.mock = true;
    else if (a === '--no-auto') flags.auto = false;
    else if (a.startsWith('--backend=')) flags.backend = a.slice('--backend='.length);
    else if (a === '--backend') flags.backend = args[++i];
    else if (a.startsWith('--session=')) flags.session = a.slice('--session='.length);
    else if (a === '--session') flags.session = args[++i];
  }
  return flags;
}

function log(flags, ...a) { if (!flags.quiet) console.log(...a); }

// 기존 markdown 파일을 dedup 컨텍스트로 분석기에 전달.
// 같은 lesson을 두 번 추출하지 않도록.
function existingForDedup() {
  const out = { knowledge: '', gotchas: '' };
  try { out.knowledge = fs.readFileSync(cfg.GLOBAL_KNOWLEDGE, 'utf8'); } catch {}
  try { out.gotchas = fs.readFileSync(cfg.GLOBAL_GOTCHAS, 'utf8'); } catch {}
  return out;
}

function buildAnalyzerPrompt(promptText, existing, t) {
  const exBlock = `<existing>\n# knowledge.md\n${existing.knowledge}\n\n# gotchas.md\n${existing.gotchas}\n</existing>`;
  const txBlock = `<transcript file="${t.source}" total_lines="${t.totalLines}" slice_from="${t.sliceFrom}">\n${JSON.stringify(t.turns, null, 2)}\n</transcript>`;
  return `${promptText}\n\n---\n\n${exBlock}\n\n${txBlock}\n\nReturn the JSON array now. No prose, no markdown fences.`;
}

function mockExtract() {
  return [{
    type: 'gotcha',
    category: 'api_quirk',
    title: 'Sample mock gotcha — replace with real run',
    context: 'Mock entry from --mock so you can verify the pipeline without an LLM call.',
    insight: 'Real entries come from `claude-distill analyze` against an actual session.',
    basis: 'Generated by lib/analyze.js mockExtract().',
    application: 'Run `claude-distill analyze` after a real session to replace this.',
    tags: ['mock', 'sample'],
    confidence: 'high',
  }];
}

function callClaudeCli(promptText) {
  try {
    return execFileSync('claude', ['--print'], {
      input: promptText,
      timeout: 120000,
      maxBuffer: 16 * 1024 * 1024,
      encoding: 'utf8',
    });
  } catch (e) {
    if (e.code === 'ENOENT') {
      const hint = [
        '`claude` CLI를 PATH에서 찾을 수 없습니다.',
        '',
        '두 가지 해결 옵션:',
        '  1) CLI 설치:  npm install -g @anthropic-ai/claude-code',
        '  2) API key 사용:  export ANTHROPIC_API_KEY=sk-ant-...',
        '                    claude-distill analyze --backend=api',
        '',
        'IDE 빌트인 Claude(Cursor / VS Code 익스텐션)는 PATH에 노출되지 않습니다 —',
        '그래서 별도 CLI 설치 또는 API key가 필요합니다. transcript 자체는',
        '익스텐션도 ~/.claude/projects/에 저장하므로 distill이 읽을 수 있습니다.',
      ].join('\n');
      throw new Error(hint);
    }
    throw new Error('claude CLI 실행 실패: ' + (e.stderr || e.message || String(e)));
  }
}

// Anthropic API 직접 호출 — Claude Code CLI 없는 환경 (Cursor / VS Code
// 익스텐션 사용자) 용. Node 18+의 빌트인 fetch 사용.
async function callClaudeApi(promptText) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY 환경변수 미설정. https://console.anthropic.com/ 에서 키 발급 후 export.');
  }
  const model = process.env.CLAUDE_DISTILL_MODEL || 'claude-sonnet-4-6';
  let res;
  try {
    res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model,
        max_tokens: 4096,
        messages: [{ role: 'user', content: promptText }],
      }),
    });
  } catch (e) {
    throw new Error('Anthropic API 네트워크 호출 실패: ' + e.message);
  }
  if (!res.ok) {
    const body = await res.text();
    throw new Error('Anthropic API ' + res.status + ': ' + body.slice(0, 400));
  }
  const data = await res.json();
  const block = (data.content || []).find((c) => c.type === 'text');
  if (!block) throw new Error('Anthropic API 응답에 text block 없음');
  return block.text;
}

// backend 결정: 'auto'면 환경변수 보고 결정. CLI 없는 사용자 (익스텐션
// 전용)도 API key만 있으면 자동으로 api 백엔드.
async function callBackend(promptText, backend) {
  if (backend === 'cli') return callClaudeCli(promptText);
  if (backend === 'api') return await callClaudeApi(promptText);
  // 'auto'
  if (process.env.ANTHROPIC_API_KEY) return await callClaudeApi(promptText);
  return callClaudeCli(promptText);
}

function tryParseJson(s) {
  let t = s.trim()
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/, '')
    .replace(/```\s*$/, '')
    .trim();
  const start = t.indexOf('[');
  const end = t.lastIndexOf(']');
  if (start === -1 || end === -1 || end <= start) return null;
  try { return JSON.parse(t.slice(start, end + 1)); } catch { return null; }
}

function transcriptHash(t) {
  const h = crypto.createHash('sha1');
  h.update(JSON.stringify(t.turns));
  return h.digest('hex').slice(0, 12);
}

// 같은 세션 같은 슬라이스면 중복 분석 방지 (Hook이 여러 번 호출돼도 안전).
function readDedupLog() {
  const f = path.join(cfg.STATE_DIR, 'analyzed.json');
  if (!fs.existsSync(f)) return new Set();
  try { return new Set(JSON.parse(fs.readFileSync(f, 'utf8'))); } catch { return new Set(); }
}
function writeDedupLog(set) {
  cfg.ensureStateDir();
  const f = path.join(cfg.STATE_DIR, 'analyzed.json');
  fs.writeFileSync(f, JSON.stringify([...set], null, 2) + '\n');
}

async function run(args) {
  const flags = parseFlags(args);
  cfg.ensureStateDir();

  let file = flags.session || transcript.latestSessionFile();
  let t;
  let sessionId;
  if (flags.mock && !file) {
    file = '<mock-session>';
    t = { source: file, turns: [], totalLines: 0, sliceFrom: 0, commandMarkers: [] };
    sessionId = 'mock-' + Date.now();
    log(flags, 'Mock 모드 — 실제 세션 없이 진행');
  } else {
    if (!file) { log(flags, '세션 jsonl을 찾을 수 없음 (' + cfg.PROJECTS_DIR + ')'); return; }
    if (!fs.existsSync(file)) { log(flags, '세션 파일 없음: ' + file); return; }
    t = transcript.extractRelevant(file);
    if (!t.turns.length && !flags.mock) { log(flags, '분석할 turn 없음'); return; }
    log(flags, '분석: ' + path.basename(file) + ' · ' + t.turns.length + ' turns');
    sessionId = path.basename(file, '.jsonl');
  }

  const dedupKey = sessionId + ':' + transcriptHash(t);
  const seen = readDedupLog();
  if (seen.has(dedupKey)) {
    log(flags, '이 세션 슬라이스는 이미 분석됨 — 새로 추가할 것 없음');
    return;
  }

  // LLM 호출
  let candidates;
  if (flags.mock) {
    candidates = mockExtract();
  } else {
    const prompt = fs.readFileSync(cfg.PROMPT_FILE, 'utf8');
    const existing = existingForDedup();
    const fullPrompt = buildAnalyzerPrompt(prompt, existing, t);
    if (flags.dryRun) {
      log(flags, '[--dry-run] prompt 준비됨 (' + fullPrompt.length + ' chars). LLM 호출 생략.');
      return;
    }
    let raw;
    try { raw = await callBackend(fullPrompt, flags.backend); }
    catch (e) { log(flags, '분석 실패: ' + e.message); return; }
    candidates = tryParseJson(raw) || [];
  }

  if (!Array.isArray(candidates) || !candidates.length) {
    log(flags, '추출할 만한 entry 없음 (빈 배열도 정상 응답)');
    seen.add(dedupKey);
    writeDedupLog(seen);
    return;
  }

  // 자동 누적 (기본 동작) — confidence:high만, 나머지는 drop
  if (flags.auto) {
    const cwd = process.cwd();
    let appended = 0;
    let dropped = 0;
    for (const c of candidates) {
      if (c.confidence !== 'high') { dropped++; continue; }
      const annotated = {
        id: crypto.randomUUID(),
        ...c,
        scope: 'global',
        source: {
          sessionId,
          project: path.basename(cwd),
          cwd,
          timestamp: new Date().toISOString(),
          relatedCommands: c.related_commands || [],
        },
      };
      try {
        const dest = store.appendEntry(annotated);
        appended++;
        log(flags, '  ✓ ' + (c.title || c.id) + ' → ' + dest);
      } catch (err) {
        log(flags, '  실패: ' + (c.title || c.id) + ' — ' + err.message);
      }
    }
    log(flags, `자동 추가 ${appended}건${dropped ? ` · 신뢰도 부족 ${dropped}건 drop` : ''}`);
  } else {
    // --no-auto — JSON 그대로 stdout (디버깅 용도)
    process.stdout.write(JSON.stringify(candidates, null, 2) + '\n');
  }

  seen.add(dedupKey);
  writeDedupLog(seen);
}

module.exports = { run };
