// `claude-distill analyze [--session=path] [--quiet]`
//
// Pulls the latest (or named) session transcript, asks Claude to extract
// candidates via the prompt in prompts/extract.md, and appends the result
// to ~/.claude/.distill/pending.json. Idempotent across re-runs of the
// same session (uses session uuid + transcript hash as a dedup key).
//
// Default invoker: the SessionEnd hook. --quiet suppresses console output
// so the hook doesn't pollute the user's terminal.

const fs = require('fs');
const path = require('path');
const { execFile, execFileSync } = require('child_process');
const crypto = require('crypto');
const cfg = require('./config');
const transcript = require('./transcript');

function parseFlags(args) {
  const flags = { quiet: false, session: null, dryRun: false, mock: false };
  for (let i = 0; i < args.length; i++) {
    const a = args[i];
    if (a === '--quiet') flags.quiet = true;
    else if (a === '--dry-run') flags.dryRun = true;
    else if (a === '--mock') flags.mock = true;
    else if (a.startsWith('--session=')) flags.session = a.slice('--session='.length);
    else if (a === '--session') flags.session = args[++i];
  }
  return flags;
}

function log(flags, ...args) { if (!flags.quiet) console.log(...args); }

function existingForDedup() {
  const out = { knowledge: '', gotchas: '' };
  try { out.knowledge = fs.readFileSync(cfg.GLOBAL_KNOWLEDGE, 'utf8'); } catch {}
  try { out.gotchas = fs.readFileSync(cfg.GLOBAL_GOTCHAS, 'utf8'); } catch {}
  return out;
}

function buildAnalyzerPrompt(promptText, existing, transcriptObj) {
  const exBlock = `<existing>\n# knowledge.md\n${existing.knowledge}\n\n# gotchas.md\n${existing.gotchas}\n</existing>`;
  const txBlock = `<transcript file="${transcriptObj.source}" total_lines="${transcriptObj.totalLines}" slice_from="${transcriptObj.sliceFrom}">\n${JSON.stringify(transcriptObj.turns, null, 2)}\n</transcript>`;
  return `${promptText}\n\n---\n\n${exBlock}\n\n${txBlock}\n\nReturn the JSON array now. No prose, no markdown fences.`;
}

// Mock extractor — used by --mock flag and when the `claude` CLI isn't
// available. Returns a fixed sample so the rest of the pipeline can be
// exercised without hitting the API.
function mockExtract() {
  return [
    {
      type: 'gotcha',
      category: 'api_quirk',
      title: 'Sample mock gotcha — replace with real run',
      context: 'This is a mock entry produced by --mock so you can exercise the review flow without calling Claude.',
      insight: 'Real entries come from `claude-distill analyze` against an actual session.',
      basis: 'Generated by lib/analyze.js mockExtract().',
      application: 'Run `claude-distill analyze` after a real session to replace this.',
      tags: ['mock', 'sample'],
      confidence: 'low',
    },
  ];
}

function callClaudeCli(promptText, flags) {
  // Pipe the prompt to `claude` via stdin. The CLI prints assistant
  // output to stdout. Sets `--print` for non-interactive single-shot mode
  // when available; otherwise reads default behavior.
  try {
    const out = execFileSync('claude', ['--print'], {
      input: promptText,
      timeout: 120000,
      maxBuffer: 16 * 1024 * 1024,
      encoding: 'utf8',
    });
    return out;
  } catch (e) {
    if (e.code === 'ENOENT') {
      const hint = [
        '`claude` CLI not found in PATH.',
        '',
        'Three ways to fix:',
        '  1. Install Claude Code CLI:',
        '       npm install -g @anthropic-ai/claude-code',
        '     (or follow https://docs.claude.com/en/docs/claude-code )',
        '',
        '  2. Use the Anthropic API directly (set ANTHROPIC_API_KEY):',
        '       export ANTHROPIC_API_KEY=sk-ant-...',
        '       claude-distill analyze --backend=api',
        '     (--backend=api support coming in v0.2)',
        '',
        '  3. Run with --mock to exercise the review flow without an LLM:',
        '       claude-distill analyze --mock',
      ].join('\n');
      throw new Error(hint);
    }
    throw new Error('claude CLI failed: ' + (e.stderr || e.message || String(e)));
  }
}

function tryParseJson(s) {
  // The model occasionally wraps in code fences despite instructions —
  // strip them, then look for the first [ … ] balanced array.
  let t = s.trim();
  t = t.replace(/^```json\s*/i, '').replace(/^```\s*/, '').replace(/```\s*$/, '').trim();
  // Find the first '[' and matching ']'.
  const start = t.indexOf('[');
  const end = t.lastIndexOf(']');
  if (start === -1 || end === -1 || end <= start) return null;
  const slice = t.slice(start, end + 1);
  try { return JSON.parse(slice); } catch { return null; }
}

function readPending() {
  if (!fs.existsSync(cfg.PENDING_FILE)) return [];
  try { return JSON.parse(fs.readFileSync(cfg.PENDING_FILE, 'utf8')); } catch { return []; }
}
function writePending(arr) {
  cfg.ensureStateDir();
  fs.writeFileSync(cfg.PENDING_FILE, JSON.stringify(arr, null, 2) + '\n');
}

function transcriptHash(t) {
  const h = crypto.createHash('sha1');
  h.update(JSON.stringify(t.turns));
  return h.digest('hex').slice(0, 12);
}

function run(args) {
  const flags = parseFlags(args);
  cfg.ensureStateDir();

  let file = flags.session || transcript.latestSessionFile();
  let t;
  let sessionId;
  if (flags.mock && !file) {
    // Mock can synthesize a one-turn fake session so the smoke test
    // works on a clean machine.
    file = '<mock-session>';
    t = { source: file, turns: [], totalLines: 0, sliceFrom: 0, commandMarkers: [] };
    sessionId = 'mock-' + Date.now();
    log(flags, 'Mock mode — no real session needed.');
  } else {
    if (!file) {
      log(flags, 'No session JSONL found under ' + cfg.PROJECTS_DIR);
      return;
    }
    if (!fs.existsSync(file)) {
      log(flags, 'Session file not found: ' + file);
      return;
    }
    log(flags, 'Analyzing: ' + file);
    t = transcript.extractRelevant(file);
    if (!t.turns.length && !flags.mock) {
      log(flags, 'No turns to analyze.');
      return;
    }
    log(flags, `  ${t.turns.length} turns (slice from index ${t.sliceFrom} of ${t.totalLines})`);
    sessionId = path.basename(file, '.jsonl');
  }
  const txHash = transcriptHash(t);
  const dedupKey = sessionId + ':' + txHash;

  // Skip if we already analyzed this exact slice.
  const existingPending = readPending();
  if (existingPending.some((e) => e._dedupKey === dedupKey)) {
    log(flags, 'Already analyzed (dedup key matches). Use --session to force a different file.');
    return;
  }

  let candidates;
  if (flags.mock) {
    candidates = mockExtract();
  } else {
    const prompt = fs.readFileSync(cfg.PROMPT_FILE, 'utf8');
    const existing = existingForDedup();
    const fullPrompt = buildAnalyzerPrompt(prompt, existing, t);
    if (flags.dryRun) {
      log(flags, '[--dry-run] Prompt prepared (' + fullPrompt.length + ' chars). Skipping CLI.');
      return;
    }
    let raw;
    try { raw = callClaudeCli(fullPrompt, flags); }
    catch (e) {
      log(flags, 'Analysis failed: ' + e.message);
      return;
    }
    candidates = tryParseJson(raw) || [];
  }

  if (!Array.isArray(candidates) || !candidates.length) {
    log(flags, 'No candidates extracted. (Empty array is a valid answer.)');
    return;
  }

  // Annotate with source + dedup key and append.
  const cwd = process.cwd();
  const annotated = candidates.map((c) => ({
    id: crypto.randomUUID(),
    ...c,
    source: {
      sessionId,
      project: path.basename(cwd),
      cwd,
      timestamp: new Date().toISOString(),
      relatedCommands: c.related_commands || [],
    },
    _dedupKey: dedupKey,
    _stagedAt: new Date().toISOString(),
  }));

  const merged = [...existingPending, ...annotated];
  writePending(merged);

  log(flags, `Staged ${annotated.length} candidate(s). Run 'claude-distill review' to walk through.`);
}

module.exports = { run };
